apiVersion: v1
data:
  values.yaml: bmZzOgogICBzZXJ2ZXI6IDEwLjI0MC4xNjMuMTY2CiAgIHBhdGg6IC9jZG90dm9sX2RmdzAyX29rZQpzdG9yYWdlQ2xhc3M6CiAgIG5hbWU6IG9rZS1uZnMKICAgZGVmYXVsdENsYXNzOiB0cnVlCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: external-nfs-client-provisioner-secret
  namespace: oke-system